.TH LIBCONTACTS_PGPKEY_DESTROY 3 LIBCONTACTS
.SH NAME
libcontacts_pgpkey_destroy \- Deallocate memory for a contact PGP-key fingerprint entry
.SH SYNOPSIS
.nf
#include <libcontacts.h>

void libcontacts_pgpkey_destroy(struct libcontacts_pgpkey *\fIentry\fP);
.fi
.PP
Link with
.IR -lcontacts .

.SH DESCRIPTION
The
.BR libcontacts_pgpkey_destroy ()
function deallocates the memory stored in
.IR *entry .
The caller must manually call
.BR free (3)
on the pointer
.I entry
afterwards if it is a freeable pointer.

.SH RETURN VALUE
None.

.SH ERRORS
None.

.SH SEE ALSO
.BR libcontacts.h (0),
.BR libcontacts (7),
.BR libcontacts_contact_destroy (3)
