.TH LIBCONTACTS 7 LIBCONTACTS
.SH NAME
libcontacts \- A library for handling a simple, flexible contact list

.SH DESCRIPTION
.B libcontacts
uses the
.I ~/.config/contacts
directory to store contact information in a simple, human and
machine readable text format that can be easily manipulated
and inspected with standard tools. See
.BR contacts (5)
for information about the format contact information is
stored in. See 
.BR libcontacts.h (0)
for information about what the library provides.
